### ISSUE TITLE
Unable to join bedrock portal worlds after the 1.21.20 update

### ISSUE THREAD

**Issue by Hermet1c** [LucienHH/bedrock-portal#10]
when joining a bedrock portal world, it displays `Connecting to multiplayer game` followed by a disconnect screen with a `Internet connection issue` error
![ApplicationFrameHost_vQWWoKmCBp](https://github.com/user-attachments/assets/41283ff4-674d-410f-b46c-4eb7dc404022)

**Comment by LucienHH** [comment]
Dupe of #9 . Will leave a comment there addressing this issue. Thanks!
