### ISSUE TITLE
Portal doesn't transfer after the new update

### ISSUE THREAD

**Issue by Atomic69420** [LucienHH/bedrock-portal#9]
Once attempting to connect to a friend connect session you will most likely be prompted with a disconnection message saying something like "Check your internet connection", after a while. I have tested this with both a server and locally and I have also asked other people to try connect as well but they could not connect. I also tried changing the IP of which server it transfers to so I chose something like lifeboat but that did not work.

**Comment by LucienHH** [comment]
Hi, Nethernet support has been implemented. Please keep in mind this is a very rushed implementation so that you guys can get your servers back up and running. You will most likely encounter bugs and unexpected behaviour whilst using v0.7.0, when you do please open an issue.

**Comment by LucienHH** [comment]
Fixed in v0.7.0. Please open another ticket if you encounter any problems.
